name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: "dash-plotly2"
          heroku_email: "tuanmanh@gmail.com"
          usedocker: true
